from __future__ import annotations

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_prefix="AUTODEFENSE_",
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    environment: str = "local"
    log_level: str = "INFO"

    redis_url: str = "redis://redis:6379/0"
    redis_stream_key: str = "autodefense:events"
    redis_consumer_group: str = "dashboard"

    # API key for authenticating dashboard / programmatic access.
    # Auto-generated by start.sh if left empty.
    api_key: str | None = None

    # HMAC key for scanner payload signing (shared secret between scanner + backend).
    # Auto-generated by start.sh if left empty.
    scanner_hmac_key: str | None = None

    # CORS allowed origins (comma-separated for env var).
    cors_origins: str = "http://localhost:3000,http://127.0.0.1:3000"

    # When > 0, rate limiting uses the leftmost address in X-Forwarded-For (append-style
    # proxies). Only enable when clients cannot reach the app except via trusted proxies.
    trusted_proxy_hops: int = 0

    # Optional LLM classification (OFF by default; system remains fully runnable without it)
    llm_enabled: bool = False
    llm_provider: str = "none"
    llm_api_key: str | None = None
    llm_model: str = "gpt-4.1-mini"

    # Risk thresholds
    risk_allow_max: int = 30
    risk_monitor_max: int = 60
    risk_sanitize_max: int = 80

    # Self-healing controls
    self_heal_enabled: bool = True
    self_heal_max_rule_growth: int = 50

    # Data protection (at-rest in Redis)
    data_encryption_enabled: bool = True
    data_key_b64: str | None = None

    # Sealed transport (client->backend payload encryption; on by default)
    transport_seal_enabled: bool = True
    transport_key_b64: str | None = None

    # Connection limits
    max_ws_connections: int = 50
    sse_timeout_seconds: int = 3600

    @property
    def cors_origin_list(self) -> list[str]:
        return [o.strip() for o in self.cors_origins.split(",") if o.strip()]


settings = Settings()

